# Generated by Django 6.0.2 on 2026-03-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('specialty', models.CharField(choices=[('Обща медицина', 'Обща медицина'), ('Кардиология', 'Кардиология'), ('Педиатрия', 'Педиатрия'), ('Дерматология', 'Дерматология'), ('Ортопедия', 'Ортопедия'), ('Неврология', 'Неврология')], max_length=32)),
                ('doctor', models.CharField(choices=[('Д-р Елена Тодорова', 'Д-р Елена Тодорова'), ('Д-р Николай Петров', 'Д-р Николай Петров'), ('Д-р Анна Георгиева', 'Д-р Анна Георгиева'), ('Д-р Виктор Иванов', 'Д-р Виктор Иванов')], max_length=64)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Чакаща'), ('confirmed', 'Потвърдена'), ('cancelled', 'Отказана')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
