# Generated by Django 6.0.2 on 2026-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_group',
            field=models.CharField(choices=[('Пациент на Д-р Георги Цветанов - осигурен', 'Пациент на Д-р Георги Цветанов - осигурен'), ('Пациент на Д-р Георги Цветанов - неосигурен', 'Пациент на Д-р Георги Цветанов - неосигурен'), ('Платен прием', 'Платен прием')], default='Пациент на Д-р Георги Цветанов - осигурен', max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_reason',
            field=models.CharField(choices=[('Преглед', 'Преглед'), ('Профилактичен преглед', 'Профилактичен преглед'), ('Издаване на рецепти', 'Издаване на рецепти'), ('Издаване на медицински удостоверения', 'Издаване на медицински удостоверения')], default='Преглед', max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Д-р Георги Цветанов', 'Д-р Георги Цветанов')], max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialty',
            field=models.CharField(choices=[('Обща медицина (Личен лекар)', 'Обща медицина (Личен лекар)'), ('Ехографска диагностика', 'Ехографска диагностика')], max_length=32),
        ),
    ]
