# Generated by Django 6.0.2 on 2026-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_patient_group_appointment_visit_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visit_reason',
            field=models.CharField(choices=[('Преглед', 'Преглед'), ('Профилактичен преглед', 'Профилактичен преглед'), ('Издаване на рецепти', 'Издаване на рецепти'), ('Издаване на медицински удостоверения', 'Издаване на медицински удостоверения'), ('Ехография на коремни органи', 'Ехография на коремни органи')], default='Преглед', max_length=64),
        ),
    ]
